name: id_gen
description: A standartized set of IDs generators.
repository: https://github.com/signmotion/id_gen

topics:
  - generator
  - id
  - uid
  - uuid
  - random

# Format:
#   version: major.minor.patch
# You can calculate the number version code by this formula:
#   code = m[A]jor * 100 * 100 + m[I]nor * 100 + [P]atch
# Otherwise: +AAIIPP
version: 0.2.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  test: ^1.25.1
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
