name: id_gen
description: A set of IDs generators.
version: 0.2.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
